### PR TITLE
add --recurse-submodules for installation section

### PR DESCRIPTION
**Pull request by Jipok**
Although in my opinion submodules is not very convenient (for you), it is still preferable than what was before.

### CODE REVIEW

**Review by itsPreto — APPROVED** [review]

**Comment by itsPreto** [comment]
@Jipok Convenience is a tradeoff I'm okay with for the time being-- tho I have plans to eventually allow for custom backends as opposed to being reliant on llama.cpp. If you have any ideas/suggestions on how to simplify the whole [or parts of the setup I'd love to hear them. I'll be creating a discord space at some point this week.

**Comment by Jipok** [comment]
> If you have any ideas/suggestions on how to simplify the whole [or parts of the setup I'd love to hear them.

* If you are comfortable with submodule then accept this pr)
* Add the llama.cpp building to Getting Started. Let there be a mention of different build options and a link to the project, but I do not recommend sending the user "go figure out how to build that project." Add at least a simple `make` call.
* Add an cli argument to specify the path to the model. This is a much easier option than changing the source code. I myself am not against this practice, but only when the variable constants are moved to the beginning of the file and are obvious to the user([like this](https://github.com/Jipok/TelegramRetranslator/blob/384bac5ccdf7bed34145104fbfe155853e731418/retranslator.py#L10)). And just in order not to complicate the project by reading command line arguments, but you already have this part, so it's strange that there is no way to specify the model and you have to look for a specific line somewhere deep in the file (inconvenient and not obvious for non-programmers)
* The main file has an executable flag, I was disappointed when it ran itself with bash. Add shebang:
изображение
* Change the requirements.txt to be less restrictive. You don't really need specific package versions with absolute precision. To get started, at least use the same numpy version as llama.cpp.

**Comment by Jipok** [comment]
In `Model Download` section:
The **7B** Llama-2 based model [TheBloke/WizardCoder-Python-**13B**-V1.0-GGUF](https://huggingface.co/TheBloke/WizardCoder-Python-13B-V1.0-GGUF) is a model fine-tuned by [a kind redditor](https://www.reddit.com/r/LocalLLaMA/comments/156htzy/i_made_llama2_7b_into_a_really_useful_coder/)

Some very strange sentence with several logical errors. It seems you had a link to another model before.

**Comment by Jipok** [comment]
изображение
This funny

**Comment by Jipok** [comment]
The first thing the user sees after launch is:
изображение
I think many, like me, will try to open http://127.0.0.1:8081 and get:
изображение
Make it obvious which link to open, preferably hide the info from llama.cpp
Perhaps you should automatically open the desired link in the browser. Although I didn’t like it before, many projects do this and I’m used to it.

**Comment by Jipok** [comment]
* Add an icon tooltip. It was not obvious to me what the arrows should do.
изображение
* Highlight code in realtime:
изображение
* Allow the user to scroll through the chat history while the model writes, at the moment, every time the response from the model changes, the scrollbar flies down.

**Comment by itsPreto** [comment]
I addressed most of the issues-- I'll be merging the PR so feel free to open an issue for the outstanding changes. Thanks a bunch!

**Pull request merged**
